"""
Research dashboard shown beneath the prediction workspace.

This page introduces LungOracle, explains the feature groups,
summarises the dataset and illustrates the modelling pipeline.
"""

from ui.components import (
    section_header,
    feature_card,
    metric_card,
    pipeline_step,
    workflow_arrow
)


def get_dashboard():

    html = []

    # =====================================================
    # Section Header
    # =====================================================

    html.append("""

<div class="lo-section" id="research">

""")

    html.append(

        section_header(

            kicker="Research Platform",

            title="Molecular Survival Prediction Beyond Clinical Staging",

            description="""
Traditional TNM staging cannot fully explain the large variability
observed in patient survival. LungOracle combines transcriptomic
signatures, tumour dysregulation, immune microenvironment and
clinical variables into a leakage-free ensemble machine learning
framework for personalised prognosis.
"""

        )

    )

    # =====================================================
    # Feature Cards
    # =====================================================

    html.append("""

<div class="lo-grid-4">

""")

    html.append(

        feature_card(

            "🧬",

            "Gene Expression",

            """
72 survival-associated genes selected from TCGA-LUAD
transcriptomic profiling.
"""

        )

    )

    html.append(

        feature_card(

            "📈",

            "Tumour Dysregulation",

            """
Gene expression deviations computed relative to
healthy GTEx lung tissue.
"""

        )

    )

    html.append(

        feature_card(

            "🛡",

            "Immune Landscape",

            """
22 immune cell populations estimated using
CIBERSORT immune deconvolution.
"""

        )

    )

    html.append(

        feature_card(

            "👤",

            "Clinical Variables",

            """
Age, biological sex and pathological stage
integrated with molecular predictors.
"""

        )

    )

    html.append("""

</div>

""")

    # =====================================================
    # Pipeline
    # =====================================================

    html.append("""

<br><br>

<div class="lo-card" style="padding:42px;">

<h2 style="margin-top:0;">
Research Pipeline
</h2>

<div class="lo-pipeline">

""")

    html.append(pipeline_step("🧬", "RNA-seq"))
    html.append(workflow_arrow())

    html.append(pipeline_step("⚙️", "Feature Engineering"))
    html.append(workflow_arrow())

    html.append(pipeline_step("🤖", "Ensemble AI"))
    html.append(workflow_arrow())

    html.append(pipeline_step("📊", "Risk Prediction"))
    html.append(workflow_arrow())

    html.append(pipeline_step("🔍", "SHAP"))

    html.append("""

</div>

</div>

""")

    # =====================================================
    # Dataset Metrics
    # =====================================================

    html.append("""

<br><br>

<div class="lo-grid-4">

""")

    html.append(metric_card("478", "Patients"))
    html.append(metric_card("20,502", "Genes"))
    html.append(metric_card("124", "Final Features"))
    html.append(metric_card("4", "Validation Cohorts"))

    html.append("""

</div>

""")

    # =====================================================
    # Disclaimer
    # =====================================================

    html.append("""

<br><br>

<div class="lo-card" style="padding:28px;">

<h3 style="margin-top:0;">
Research Use Only
</h3>

<p style="color:#64748b;line-height:1.9;">

LungOracle is intended exclusively for research and educational
purposes.

Predictions generated by this platform should not be used for
clinical diagnosis or treatment decisions.

Always consult qualified healthcare professionals before making
medical decisions.

</p>

</div>

""")

    html.append("""

</div>

""")

    return "".join(html)