"""
Professional footer for LungOracle.

Displayed at the bottom of the application.
"""

from datetime import datetime


def get_footer():

    year = datetime.now().year

    return f"""

<div style="
margin-top:80px;
background:#0f172a;
color:white;
font-family:-apple-system,BlinkMacSystemFont,Inter,Arial,sans-serif;
">

<div class="lo-section" style="padding-top:60px;padding-bottom:40px;">

<div style="
display:grid;
grid-template-columns:2fr 1fr 1fr;
gap:60px;
align-items:start;
">

<!-- ================================================= -->
<!-- LEFT -->
<!-- ================================================= -->

<div>

<div style="
display:flex;
align-items:center;
gap:16px;
margin-bottom:20px;
">

<div style="
width:56px;
height:56px;
border-radius:16px;
background:linear-gradient(135deg,#2563eb,#1d4ed8);
display:flex;
justify-content:center;
align-items:center;
font-size:28px;
">

🧬

</div>

<div>

<div style="
font-size:30px;
font-weight:800;
letter-spacing:-1px;
">

LungOracle

</div>

<div style="
font-size:14px;
color:#94a3b8;
margin-top:4px;
">

AI-powered Molecular Survival Prediction

</div>

</div>

</div>

<div style="
font-size:15px;
line-height:1.9;
color:#cbd5e1;
max-width:620px;
">

LungOracle is an explainable artificial intelligence platform
for personalised survival prediction in lung adenocarcinoma.

The system integrates transcriptomics, tumour dysregulation,
immune microenvironment and clinical variables using a
leakage-free ensemble machine learning framework.

</div>

</div>



<!-- ================================================= -->
<!-- RESEARCH -->
<!-- ================================================= -->

<div>

<div style="
font-size:18px;
font-weight:700;
margin-bottom:18px;
">

Research

</div>

<div style="color:#cbd5e1;line-height:2;">

<div>• TCGA-LUAD</div>

<div>• GTEx Lung</div>

<div>• CIBERSORT</div>

<div>• SHAP Explainability</div>

<div>• Ensemble Learning</div>

</div>

</div>



<!-- ================================================= -->
<!-- LINKS -->
<!-- ================================================= -->

<div>

<div style="
font-size:18px;
font-weight:700;
margin-bottom:18px;
">

Resources

</div>

<div style="line-height:2;">

<a
href="https://github.com/ParthShringarpure09/Lung_adenocarcinoma_survival"
target="_blank"
style="color:#cbd5e1;text-decoration:none;"
>

GitHub Repository

</a>

<br>

<a
href="#research"
style="color:#cbd5e1;text-decoration:none;"
>

Research Overview

</a>

<br>

<a
href="#"
style="color:#cbd5e1;text-decoration:none;"
>

Methods

</a>

<br>

<a
href="#"
style="color:#cbd5e1;text-decoration:none;"
>

Documentation

</a>

</div>

</div>

</div>



<hr style="
margin:50px 0 30px;
border:none;
border-top:1px solid rgba(255,255,255,.08);
">



<div style="
display:flex;
justify-content:space-between;
align-items:center;
flex-wrap:wrap;
gap:20px;
">

<div style="
font-size:13px;
color:#94a3b8;
">

© {year} LungOracle • University of Glasgow

</div>

<div style="
display:flex;
gap:12px;
flex-wrap:wrap;
">

<span class="lo-badge">

Research Use Only

</span>

<span class="lo-badge">

Version 1.0

</span>

<span class="lo-badge">

Explainable AI

</span>

</div>

</div>



<div style="
margin-top:28px;
padding:22px;
border-radius:18px;
background:rgba(255,255,255,.05);
font-size:13px;
line-height:1.9;
color:#cbd5e1;
">

<strong>Disclaimer:</strong>

LungOracle is intended solely for research and educational
purposes.

Predictions generated by this software are not approved for
clinical diagnosis or treatment planning and should not replace
professional medical judgement.

</div>

</div>

</div>

"""