"""
Sidebar components for LungOracle.

Shared between Demo Patients and Predict Mode.
"""

from ui.components import (
    metric_card,
    badge,
)


# ============================================================
# Sidebar Heading
# ============================================================
def get_sidebar_heading(title="Patient Selection"):
    return f"""
    <div style="
        font-size:11px;
        font-weight:700;
        text-transform:uppercase;
        letter-spacing:.6px;
        color:#718096;
        margin-bottom:8px;
        font-family:-apple-system,BlinkMacSystemFont,Inter,Arial,sans-serif;
    ">
        {title}
    </div>
    """


# ============================================================
# Dataset Summary
# ============================================================

def get_sidebar_stats():

    return """
    <div class="lo-card" style="padding:20px;margin-top:20px;">

        <div class="lo-kicker" style="margin-bottom:16px;">
            Research Dataset
        </div>

        <div style="
            display:grid;
            grid-template-columns:1fr 1fr;
            gap:12px;
            margin-bottom:18px;
        ">

            <div class="lo-stat-card">
                <div class="lo-stat-value">478</div>
                <div class="lo-stat-label">Patients</div>
            </div>

            <div class="lo-stat-card">
                <div class="lo-stat-value">124</div>
                <div class="lo-stat-label">Features</div>
            </div>

            <div class="lo-stat-card">
                <div class="lo-stat-value">22</div>
                <div class="lo-stat-label">Immune Cells</div>
            </div>

            <div class="lo-stat-card">
                <div class="lo-stat-value">0.702</div>
                <div class="lo-stat-label">C-index</div>
            </div>

        </div>

        <div style="
            display:flex;
            flex-wrap:wrap;
            gap:8px;
        ">

            <span class="lo-badge">Leakage-Free</span>
            <span class="lo-badge">Validation</span>
            <span class="lo-badge">SHAP</span>

        </div>

    </div>
    """
# ============================================================
# Research Disclaimer
# ============================================================

def get_disclaimer():

    return """

<div class="lo-card" style="
padding:22px;
margin-top:24px;
background:#fafcff;
">

<div class="lo-kicker">

Research Use Only

</div>

<div style="
font-size:13px;
line-height:1.8;
color:#64748b;
">

LungOracle is intended exclusively for research
and educational purposes.

Predictions generated by this software are not
approved for clinical diagnosis or treatment
planning.

Always consult qualified healthcare professionals
before making medical decisions.

</div>

</div>

"""